apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
        - name: kafka-broker
          image: bashj79/kafka-kraft
          stdin: true
          tty: true