apiVersion: v1
kind: Service
metadata:
  name: oia-pce-svc
  labels:
    app: oia-pce-app
spec:
  type: NodePort
  ports:
    - name: drpy-port
      port: 40000
      protocol: TCP
      targetPort: 40000
  selector:
    app: oia-pce-app