apiVersion: apps/v1
kind: Deployment
metadata:
  name: ols-controller
  labels:
    app: ols-controller-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ols-controller-app
  template:
    metadata:
      labels:
        app: ols-controller-app
    spec:
      containers:
        - name: ols-controller
          image: tqhuy812/ols-ofc2023:1.0.0
          stdin: true
          tty: true